/**
 * Generated by orval v8.5.3
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Get all active trade suggestions
 */
export const GetActiveSuggestionsResponseItem = zod.object({
  id: zod.string(),
  symbol: zod.string(),
  name: zod.string(),
  exchange: zod.string(),
  direction: zod.enum(["BUY", "SELL"]),
  tradeType: zod.enum(["INTRADAY", "SWING"]),
  entryPrice: zod.number(),
  stopLoss: zod.number(),
  target1: zod.number(),
  target2: zod.number().nullish(),
  riskReward: zod.number(),
  quantity: zod.number(),
  maxRiskInr: zod.number(),
  setupType: zod.string(),
  marketRegime: zod.string(),
  reasoning: zod.string(),
  validityTill: zod.string(),
  expectedHoldMinutes: zod.number().int().nullish(),
  expiresAt: zod.coerce.date().nullish(),
  status: zod.enum(["PENDING", "ACTIVE", "TARGET_1_HIT", "TARGET_2_HIT", "STOP_HIT", "EXPIRED", "CLOSED", "REJECTED"]),
  outcomePrice: zod.number().nullish(),
  pnlInr: zod.number().nullish(),
  currentPrice: zod.number().nullish(),
  generatedAt: zod.coerce.date(),
  closedAt: zod.coerce.date().nullish(),
  stopDistancePct: zod.number().nullish(),
});
export const GetActiveSuggestionsResponse = zod.array(
  GetActiveSuggestionsResponseItem,
);

/**
 * @summary Get today's suggestions with outcomes
 */
export const GetTodaySuggestionsResponseItem = zod.object({
  id: zod.string(),
  symbol: zod.string(),
  name: zod.string(),
  exchange: zod.string(),
  direction: zod.enum(["BUY", "SELL"]),
  tradeType: zod.enum(["INTRADAY", "SWING"]),
  entryPrice: zod.number(),
  stopLoss: zod.number(),
  target1: zod.number(),
  target2: zod.number().nullish(),
  riskReward: zod.number(),
  quantity: zod.number(),
  maxRiskInr: zod.number(),
  setupType: zod.string(),
  marketRegime: zod.string(),
  reasoning: zod.string(),
  validityTill: zod.string(),
  status: zod.enum(["PENDING", "ACTIVE", "TARGET_1_HIT", "TARGET_2_HIT", "STOP_HIT", "EXPIRED", "CLOSED", "REJECTED"]),
  outcomePrice: zod.number().nullish(),
  pnlInr: zod.number().nullish(),
  currentPrice: zod.number().nullish(),
  generatedAt: zod.coerce.date(),
  closedAt: zod.coerce.date().nullish(),
  stopDistancePct: zod.number().nullish(),
});
export const GetTodaySuggestionsResponse = zod.array(
  GetTodaySuggestionsResponseItem,
);

/**
 * @summary Get paginated suggestion history
 */
export const getSuggestionHistoryQueryPageDefault = 1;
export const getSuggestionHistoryQueryLimitDefault = 50;

export const GetSuggestionHistoryQueryParams = zod.object({
  page: zod.coerce.number().default(getSuggestionHistoryQueryPageDefault),
  limit: zod.coerce.number().default(getSuggestionHistoryQueryLimitDefault),
  status: zod
    .enum(["PENDING", "ACTIVE", "TARGET_1_HIT", "TARGET_2_HIT", "STOP_HIT", "EXPIRED", "CLOSED", "REJECTED"])
    .optional(),
  setup_type: zod.string().trim().min(1).optional(),
  direction: zod.enum(["BUY", "SELL"]).optional(),
  from_date: zod.coerce.date().optional(),
  to_date: zod.coerce.date().optional(),
});

export const GetSuggestionHistoryResponse = zod.object({
  data: zod.array(
    zod.object({
      id: zod.string(),
      symbol: zod.string(),
      name: zod.string(),
      exchange: zod.string(),
      direction: zod.enum(["BUY", "SELL"]),
      tradeType: zod.enum(["INTRADAY", "SWING"]),
      entryPrice: zod.number(),
      stopLoss: zod.number(),
      target1: zod.number(),
      target2: zod.number().nullish(),
      riskReward: zod.number(),
      quantity: zod.number(),
      maxRiskInr: zod.number(),
      setupType: zod.string(),
      marketRegime: zod.string(),
      reasoning: zod.string(),
      validityTill: zod.string(),
      expectedHoldMinutes: zod.number().int().nullish(),
      expiresAt: zod.coerce.date().nullish(),
      status: zod.enum(["PENDING", "ACTIVE", "TARGET_1_HIT", "TARGET_2_HIT", "STOP_HIT", "EXPIRED", "CLOSED", "REJECTED"]),
      outcomePrice: zod.number().nullish(),
      pnlInr: zod.number().nullish(),
      currentPrice: zod.number().nullish(),
      generatedAt: zod.coerce.date(),
      closedAt: zod.coerce.date().nullish(),
      stopDistancePct: zod.number().nullish(),
    }),
  ),
  total: zod.number(),
  page: zod.number(),
  limit: zod.number(),
});

/**
 * @summary Get a single suggestion by ID
 */
export const GetSuggestionParams = zod.object({
  id: zod.coerce.string(),
});

export const GetSuggestionResponse = zod.object({
  id: zod.string(),
  symbol: zod.string(),
  name: zod.string(),
  exchange: zod.string(),
  direction: zod.enum(["BUY", "SELL"]),
  tradeType: zod.enum(["INTRADAY", "SWING"]),
  entryPrice: zod.number(),
  stopLoss: zod.number(),
  target1: zod.number(),
  target2: zod.number().nullish(),
  riskReward: zod.number(),
  quantity: zod.number(),
  maxRiskInr: zod.number(),
  setupType: zod.string(),
  marketRegime: zod.string(),
  reasoning: zod.string(),
  validityTill: zod.string(),
  expectedHoldMinutes: zod.number().int().nullish(),
  expiresAt: zod.coerce.date().nullish(),
  status: zod.enum(["PENDING", "ACTIVE", "TARGET_1_HIT", "TARGET_2_HIT", "STOP_HIT", "EXPIRED", "CLOSED", "REJECTED"]),
  outcomePrice: zod.number().nullish(),
  pnlInr: zod.number().nullish(),
  currentPrice: zod.number().nullish(),
  generatedAt: zod.coerce.date(),
  closedAt: zod.coerce.date().nullish(),
  stopDistancePct: zod.number().nullish(),
});

/**
 * @summary Overall performance statistics
 */
export const getPerformanceStatsQueryDaysDefault = 30;

export const GetPerformanceStatsQueryParams = zod.object({
  days: zod.coerce
    .number()
    .int()
    .min(1)
    .max(365)
    .default(getPerformanceStatsQueryDaysDefault),
});

export const GetPerformanceStatsResponse = zod.object({
  totalSuggestions: zod.number(),
  active: zod.number(),
  target1Hit: zod.number(),
  target2Hit: zod.number(),
  stopHit: zod.number(),
  expired: zod.number(),
  winRate: zod.number(),
  profitFactor: zod.number(),
  avgRrRealized: zod.number(),
  last10Results: zod.array(zod.enum(["WIN", "LOSS", "EXPIRED"])),
  totalPnlInr: zod.number(),
});

/**
 * @summary Performance breakdown by setup type
 */
export const GetPerformanceBySetupResponseItem = zod.object({
  setupType: zod.string(),
  count: zod.number(),
  wins: zod.number(),
  losses: zod.number(),
  winRate: zod.number(),
  profitFactor: zod.number(),
});
export const GetPerformanceBySetupResponse = zod.array(
  GetPerformanceBySetupResponseItem,
);

/**
 * @summary Daily P&L and win rate over time
 */
export const getDailyPerformanceQueryDaysDefault = 30;

export const GetDailyPerformanceQueryParams = zod.object({
  days: zod.coerce
    .number()
    .int()
    .min(1)
    .max(365)
    .default(getDailyPerformanceQueryDaysDefault),
});

export const GetDailyPerformanceResponseItem = zod.object({
  date: zod.coerce.date(),
  totalSuggestions: zod.number(),
  wins: zod.number(),
  losses: zod.number(),
  winRate: zod.number(),
  pnlInr: zod.number(),
});
export const GetDailyPerformanceResponse = zod.array(
  GetDailyPerformanceResponseItem,
);

/**
 * @summary Current market regime and VIX
 */
export const GetMarketRegimeResponse = zod.object({
  regime: zod.enum([
    "TRENDING_UP",
    "TRENDING_DOWN",
    "VOLATILE",
    "RANGING",
    "UNKNOWN",
  ]),
  sessionPhase: zod.enum(["PRE_MARKET", "MARKET", "POST_MARKET", "OFF_HOURS"]),
  isMarketOpen: zod.boolean(),
  minutesUntilOpen: zod.number().nullish(),
  indiaVix: zod.number().nullable(),
  niftyChange: zod.number().nullish(),
  updatedAt: zod.coerce.date(),
  suggestionsPaused: zod.boolean(),
  pauseReason: zod.string().nullable(),
});

/**
 * @summary Nifty price, breadth, and top sectors
 */
export const GetMarketOverviewResponse = zod.object({
  niftyPrice: zod.number().nullable(),
  niftyChangePct: zod.number().nullable(),
  advanceCount: zod.number(),
  declineCount: zod.number(),
  topSectors: zod.array(
    zod.object({
      name: zod.string(),
      changePct: zod.number(),
    }),
  ),
  isMarketOpen: zod.boolean(),
  marketOpenTime: zod.string().optional(),
  marketCloseTime: zod.string().optional(),
  upstoxFeed: zod
    .object({
      status: zod.enum([
        "idle",
        "loading",
        "partial",
        "ready",
        "unauthenticated",
        "failed",
      ]),
      authenticated: zod.boolean(),
      fetchedAt: zod.string().nullable(),
      prevClose: zod.number().nullable(),
      niftyLtp: zod.number().nullable(),
      vixLtp: zod.number().nullable(),
      niftyChangePct: zod.number().nullable(),
      note: zod.string().nullable(),
    })
    .nullable()
    .optional(),
});

/**
 * @summary Overnight scanner output for tomorrow
 */
const WatchlistItemSchema = zod.object({
  symbol: zod.string(),
  name: zod.string().nullish(),
  category: zod.enum([
    "MOMENTUM",
    "BREAKOUT_WATCH",
    "GAP_CANDIDATE",
    "INTRADAY_BUY",
    "INTRADAY_SELL",
    "AVOID",
  ]),
  condition: zod.string(),
  priority: zod.number().nullish(),
});

export const GetTomorrowWatchlistResponse = zod.object({
  forDate: zod.coerce.date(),
  momentumCandidates: zod.array(WatchlistItemSchema),
  breakoutCandidates: zod.array(WatchlistItemSchema),
  gapCandidates: zod.array(WatchlistItemSchema),
  intradayCandidates: zod.array(WatchlistItemSchema),
  avoidList: zod.array(WatchlistItemSchema),
  generatedAt: zod.coerce.date().nullable(),
});

/**
 * @summary Today's watchlist including pre-market gap candidates
 */
export const GetTodayWatchlistResponse = zod.object({
  forDate: zod.coerce.date(),
  momentumCandidates: zod.array(WatchlistItemSchema),
  breakoutCandidates: zod.array(WatchlistItemSchema),
  gapCandidates: zod.array(WatchlistItemSchema),
  intradayCandidates: zod.array(WatchlistItemSchema),
  avoidList: zod.array(WatchlistItemSchema),
  generatedAt: zod.coerce.date().nullable(),
});

/**
 * @summary Get trading configuration
 */
export const GetConfigResponse = zod.object({
  tradingCapital: zod.number(),
  maxRiskPerTradePct: zod.number(),
  maxDailyLossPct: zod.number(),
  maxOpenPositions: zod.number(),
  maxSectorExposure: zod.number(),
  minRiskReward: zod.number(),
  minDailyVolume: zod.number(),
  vixPauseThreshold: zod.number(),
  minSuggestionScore: zod.number(),
  minMtfConfluencePct: zod.number(),
  minAutoConfidencePct: zod.number(),
  brokeragePerOrderInr: zod.number(),
  slippageBps: zod.number(),
  confidenceThresholdByRegimeJson: zod.string(),
  maxSameDirectionOpenPositions: zod.number(),
  avoidFirstMinutes: zod.number(),
  avoidMiddayStartMinute: zod.number(),
  avoidMiddayEndMinute: zod.number(),
  weeklyLossLimitPct: zod.number(),
  rollingDrawdownPct: zod.number(),
  paperTradingEnabled: zod.boolean(),
  upstoxApiKey: zod.string(),
  upstoxApiSecret: zod.string(),
  upstoxDataApiKey: zod.string(),
  upstoxDataApiSecret: zod.string(),
  upstoxRedirectUri: zod.string(),
  stopLossMode: zod.string(),
});

/**
 * @summary Update trading configuration
 */
export const UpdateConfigBody = zod.object({
  tradingCapital: zod.number().positive().max(100000000).optional(),
  maxRiskPerTradePct: zod.number().positive().max(10).optional(),
  maxDailyLossPct: zod.number().positive().max(25).optional(),
  maxOpenPositions: zod.number().int().min(1).max(50).optional(),
  maxSectorExposure: zod.number().int().min(1).max(20).optional(),
  minRiskReward: zod.number().min(0.5).max(20).optional(),
  minDailyVolume: zod.number().int().min(1).max(1000000000).optional(),
  vixPauseThreshold: zod.number().min(5).max(100).optional(),
  minSuggestionScore: zod.number().min(0).max(10).optional(),
  minMtfConfluencePct: zod.number().min(0).max(100).optional(),
  minAutoConfidencePct: zod.number().min(0).max(100).optional(),
  brokeragePerOrderInr: zod.number().min(0).max(1000).optional(),
  slippageBps: zod.number().min(0).max(500).optional(),
  confidenceThresholdByRegimeJson: zod.string().max(5000).optional(),
  maxSameDirectionOpenPositions: zod.number().int().min(1).max(20).optional(),
  avoidFirstMinutes: zod.number().int().min(0).max(120).optional(),
  avoidMiddayStartMinute: zod.number().int().min(0).max(360).optional(),
  avoidMiddayEndMinute: zod.number().int().min(0).max(360).optional(),
  weeklyLossLimitPct: zod.number().min(0.5).max(50).optional(),
  rollingDrawdownPct: zod.number().min(0.5).max(80).optional(),
  paperTradingEnabled: zod.boolean().optional(),
  upstoxApiKey: zod.string().trim().max(200).optional(),
  upstoxApiSecret: zod.string().trim().max(500).optional(),
  upstoxDataApiKey: zod.string().trim().max(200).optional(),
  upstoxDataApiSecret: zod.string().trim().max(500).optional(),
  upstoxRedirectUri: zod.string().trim().url().or(zod.literal("")).optional(),
  stopLossMode: zod.enum(["FIXED", "TRAILING", "BREAKEVEN"]).optional(),
  maxDeployedCapitalPct: zod.number().min(1).max(100).optional(),
  discordWebhookUrl: zod.string().trim().max(500).optional(),
  telegramBotToken: zod.string().trim().max(500).optional(),
  telegramChatId: zod.string().trim().max(200).optional(),
});

export const UpdateConfigResponse = zod.object({
  tradingCapital: zod.number(),
  maxRiskPerTradePct: zod.number(),
  maxDailyLossPct: zod.number(),
  maxOpenPositions: zod.number(),
  maxSectorExposure: zod.number(),
  minRiskReward: zod.number(),
  minDailyVolume: zod.number(),
  vixPauseThreshold: zod.number(),
  minSuggestionScore: zod.number(),
  minMtfConfluencePct: zod.number(),
  minAutoConfidencePct: zod.number(),
  brokeragePerOrderInr: zod.number(),
  slippageBps: zod.number(),
  confidenceThresholdByRegimeJson: zod.string(),
  maxSameDirectionOpenPositions: zod.number(),
  avoidFirstMinutes: zod.number(),
  avoidMiddayStartMinute: zod.number(),
  avoidMiddayEndMinute: zod.number(),
  weeklyLossLimitPct: zod.number(),
  rollingDrawdownPct: zod.number(),
  paperTradingEnabled: zod.boolean(),
  upstoxApiKey: zod.string(),
  upstoxApiSecret: zod.string(),
  upstoxDataApiKey: zod.string(),
  upstoxDataApiSecret: zod.string(),
  upstoxRedirectUri: zod.string(),
  stopLossMode: zod.string(),
  maxDeployedCapitalPct: zod.number().optional(),
  discordWebhookUrl: zod.string().optional(),
  telegramBotToken: zod.string().optional(),
  telegramChatId: zod.string().optional(),
});

/**
 * @summary Full system status (WS, DB, Redis, scheduler)
 */
export const GetSystemStatusResponse = zod.object({
  wsConnected: zod.boolean(),
  dbConnected: zod.boolean(),
  schedulerRunning: zod.boolean(),
  upstoxAuthenticated: zod.boolean(),
  upstoxConfigured: zod.boolean(),
  paperTradingEnabled: zod.boolean().optional(),
  isMarketOpen: zod.boolean(),
  symbolsCached: zod.number(),
  activeSubscriptions: zod.number(),
  lastTickAt: zod.coerce.date().nullable(),
  dailyLossToday: zod.number(),
  dailyLossLimitHit: zod.boolean(),
});

/**
 * @summary Get Upstox OAuth authorization URL
 */
export const GetAuthUrlResponse = zod.object({
  url: zod.string(),
});

/**
 * @summary Handle Upstox OAuth callback
 */
export const HandleAuthCallbackQueryParams = zod.object({
  code: zod.coerce.string(),
  state: zod.coerce.string(),
});

export const HandleAuthCallbackResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
});

export const CreateSuggestionBody = zod.object({
  symbol: zod.string().trim().min(1).max(20),
  direction: zod.enum(["BUY", "SELL"]),
  entryPrice: zod.coerce.number().positive(),
  stopLoss: zod.coerce.number().positive(),
  target1: zod.coerce.number().positive(),
  quantity: zod.coerce.number().int().positive(),
  status: zod.enum(["PENDING", "ACTIVE", "TARGET_1_HIT", "TARGET_2_HIT", "STOP_HIT", "EXPIRED", "CLOSED", "REJECTED"]).default("PENDING").optional(),
});

export const ModifyStopLossBody = zod.object({
  stopLoss: zod.coerce.number().positive(),
});

export const ModifyTargetBody = zod.object({
  target1: zod.coerce.number().positive(),
});
