import {
  pgTable,
  uuid,
  varchar,
  text,
  decimal,
  integer,
  timestamp,
  jsonb,
  index,
} from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod/v4";

/**
 * Suggestions Table
 * Persists all trade suggestions generated by the scanning and monitoring flows.
 * Tracks trades using the `status` column (e.g. ACTIVE, TARGET_HIT, STOP_HIT, CLOSED).
 * Active suggestions are reloaded from this table on restart to maintain session consistency.
 */
export const suggestionsTable = pgTable("suggestions", {
  id: uuid("id").primaryKey().defaultRandom(),
  symbol: varchar("symbol", { length: 20 }).notNull(),
  name: varchar("name", { length: 100 }),
  exchange: varchar("exchange", { length: 10 }).notNull().default("NSE"),
  direction: varchar("direction", { length: 5 }).notNull(), // BUY | SELL
  tradeType: varchar("trade_type", { length: 10 }).notNull(), // INTRADAY | SWING
  setupType: varchar("setup_type", { length: 30 }).notNull(),
  entryPrice: decimal("entry_price", { precision: 10, scale: 2 }).notNull(),
  stopLoss: decimal("stop_loss", { precision: 10, scale: 2 }).notNull(),
  target1: decimal("target_1", { precision: 10, scale: 2 }).notNull(),
  target2: decimal("target_2", { precision: 10, scale: 2 }),
  riskReward: decimal("risk_reward", { precision: 5, scale: 2 }),
  quantity: integer("quantity").notNull(),
  maxRiskInr: decimal("max_risk_inr", { precision: 10, scale: 2 }),
  stopDistancePct: decimal("stop_distance_pct", { precision: 5, scale: 2 }),
  marketRegime: varchar("market_regime", { length: 20 }),
  confidence: integer("confidence"),
  aiScore: integer("ai_score"),
  patternScore: integer("pattern_score"),
  chronosScore: integer("chronos_score"),
  technicalScore: integer("technical_score"),
  sentimentScore: integer("sentiment_score"),
  rankingMode: varchar("ranking_mode", { length: 20 }),
  signalFactors: jsonb("signal_factors"),
  // Full 30-feature vector captured at signal time. Persisted so a model can be
  // trained on realized outcomes (copied into signal_outcomes at close).
  featureVector: jsonb("feature_vector"),
  highestPrice: decimal("highest_price", { precision: 10, scale: 2 }),
  lowestPrice: decimal("lowest_price", { precision: 10, scale: 2 }),
  atr: decimal("atr", { precision: 10, scale: 2 }),
  reasoning: text("reasoning"),
  validityTill: varchar("validity_till", { length: 10 }),
  expectedHoldMinutes: integer("expected_hold_minutes"),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  status: varchar("status", { length: 20 }).notNull().default("ACTIVE"),
  stopLossMode: varchar("stop_loss_mode", { length: 20 }),
  outcomePrice: decimal("outcome_price", { precision: 10, scale: 2 }),
  pnlInr: decimal("pnl_inr", { precision: 10, scale: 2 }),
  generatedAt: timestamp("generated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  closedAt: timestamp("closed_at", { withTimezone: true }),
  // Set by the historical outcome backfill once a closed row's result has been
  // verified against 1-minute candles for its allotted window. NULL = the live
  // tick tracker decided it (or it has not been verified yet).
  outcomeVerifiedAt: timestamp("outcome_verified_at", { withTimezone: true }),
}, (table) => ({
  statusIdx: index("suggestions_status_idx").on(table.status),
  generatedAtIdx: index("suggestions_generated_at_idx").on(table.generatedAt),
  symbolGeneratedAtIdx: index("suggestions_symbol_generated_idx").on(table.symbol, table.generatedAt),
}));

export const insertSuggestionSchema = createInsertSchema(suggestionsTable).omit(
  { id: true, generatedAt: true }
);
export const selectSuggestionSchema = createSelectSchema(suggestionsTable);
export type InsertSuggestion = z.infer<typeof insertSuggestionSchema>;
export type Suggestion = typeof suggestionsTable.$inferSelect;
