/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */

export type GetSuggestionHistoryStatus =
  (typeof GetSuggestionHistoryStatus)[keyof typeof GetSuggestionHistoryStatus];

export const GetSuggestionHistoryStatus = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  TARGET_1_HIT: "TARGET_1_HIT",
  TARGET_2_HIT: "TARGET_2_HIT",
  STOP_HIT: "STOP_HIT",
  EXPIRED: "EXPIRED",
  CLOSED: "CLOSED",
  REJECTED: "REJECTED",
} as const;
