/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */
import type { GetSuggestionHistoryDirection } from "./getSuggestionHistoryDirection";
import type { GetSuggestionHistorySetupType } from "./getSuggestionHistorySetupType";
import type { GetSuggestionHistoryStatus } from "./getSuggestionHistoryStatus";

export type GetSuggestionHistoryParams = {
  page?: number;
  limit?: number;
  status?: GetSuggestionHistoryStatus;
  setup_type?: GetSuggestionHistorySetupType;
  direction?: GetSuggestionHistoryDirection;
  from_date?: Date;
  to_date?: Date;
};
