/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */

export type MarketRegimeSessionPhase =
  (typeof MarketRegimeSessionPhase)[keyof typeof MarketRegimeSessionPhase];

export const MarketRegimeSessionPhase = {
  PRE_MARKET: "PRE_MARKET",
  MARKET: "MARKET",
  POST_MARKET: "POST_MARKET",
  OFF_HOURS: "OFF_HOURS",
} as const;
