/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */
import type { SectorPerformance } from "./sectorPerformance";

export interface MarketOverview {
  /** @nullable */
  niftyPrice: number | null;
  /** @nullable */
  niftyChangePct: number | null;
  advanceCount: number;
  declineCount: number;
  topSectors: SectorPerformance[];
  isMarketOpen: boolean;
  marketOpenTime?: string;
  marketCloseTime?: string;
}
