/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */

export type MarketRegimeRegime =
  (typeof MarketRegimeRegime)[keyof typeof MarketRegimeRegime];

export const MarketRegimeRegime = {
  TRENDING_UP: "TRENDING_UP",
  TRENDING_DOWN: "TRENDING_DOWN",
  VOLATILE: "VOLATILE",
  RANGING: "RANGING",
  UNKNOWN: "UNKNOWN",
} as const;
