/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */
import type { MarketRegimeRegime } from "./marketRegimeRegime";
import type { MarketRegimeSessionPhase } from "./marketRegimeSessionPhase";

export interface MarketRegime {
  regime: MarketRegimeRegime;
  sessionPhase: MarketRegimeSessionPhase;
  isMarketOpen: boolean;
  /** @nullable */
  minutesUntilOpen?: number | null;
  /** @nullable */
  indiaVix: number | null;
  /** @nullable */
  niftyChange?: number | null;
  updatedAt: Date;
  suggestionsPaused: boolean;
  /** @nullable */
  pauseReason: string | null;
}
