/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */
import type { PerformanceStatsLast10ResultsItem } from "./performanceStatsLast10ResultsItem";

export interface PerformanceStats {
  totalSuggestions: number;
  active: number;
  target1Hit: number;
  target2Hit: number;
  stopHit: number;
  expired: number;
  winRate: number;
  profitFactor: number;
  avgRrRealized: number;
  last10Results: PerformanceStatsLast10ResultsItem[];
  totalPnlInr: number;
}
