/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */

export type PerformanceStatsLast10ResultsItem =
  (typeof PerformanceStatsLast10ResultsItem)[keyof typeof PerformanceStatsLast10ResultsItem];

export const PerformanceStatsLast10ResultsItem = {
  WIN: "WIN",
  LOSS: "LOSS",
  EXPIRED: "EXPIRED",
} as const;
