/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */
import type { Suggestion } from "./suggestion";

export interface SuggestionHistoryPage {
  data: Suggestion[];
  total: number;
  page: number;
  limit: number;
}
