/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */
import type { SuggestionDirection } from "./suggestionDirection";
import type { SuggestionSetupType } from "./suggestionSetupType";
import type { SuggestionStatus } from "./suggestionStatus";
import type { SuggestionTradeType } from "./suggestionTradeType";

export interface Suggestion {
  id: string;
  symbol: string;
  name: string;
  exchange: string;
  direction: SuggestionDirection;
  tradeType: SuggestionTradeType;
  entryPrice: number;
  stopLoss: number;
  target1: number;
  /** @nullable */
  target2?: number | null;
  riskReward: number;
  quantity: number;
  maxRiskInr: number;
  setupType: SuggestionSetupType;
  marketRegime: string;
  reasoning: string;
  validityTill: string;
  status: SuggestionStatus;
  /** @nullable */
  outcomePrice?: number | null;
  /** @nullable */
  pnlInr?: number | null;
  /** @nullable */
  currentPrice?: number | null;
  generatedAt: Date;
  /** @nullable */
  closedAt?: Date | null;
  /** @nullable */
  stopDistancePct?: number | null;
}
