/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */

export interface SystemStatus {
  wsConnected: boolean;
  dbConnected: boolean;
  schedulerRunning: boolean;
  upstoxAuthenticated: boolean;
  isMarketOpen: boolean;
  instrumentsLoaded: number;
  activeSubscriptions: number;
  /** @nullable */
  lastTickAt: Date | null;
  dailyLossToday: number;
  dailyLossLimitHit: boolean;
}
