/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */
import type { WatchlistItem } from "./watchlistItem";

export interface TomorrowWatchlist {
  forDate: Date;
  momentumCandidates: WatchlistItem[];
  breakoutCandidates: WatchlistItem[];
  gapCandidates: WatchlistItem[];
  intradayCandidates: WatchlistItem[];
  avoidList: WatchlistItem[];
  /** @nullable */
  generatedAt: Date | null;
}
