/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */

export interface TradingConfigUpdate {
  tradingCapital?: number;
  maxRiskPerTradePct?: number;
  maxDailyLossPct?: number;
  maxOpenPositions?: number;
  maxSectorExposure?: number;
  minRiskReward?: number;
  minDailyVolume?: number;
  vixPauseThreshold?: number;
  minSuggestionScore?: number;
  minMtfConfluencePct?: number;
  upstoxApiKey?: string;
  upstoxApiSecret?: string;
  upstoxRedirectUri?: string;
}
