/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */
import type { WatchlistItemCategory } from "./watchlistItemCategory";

export interface WatchlistItem {
  symbol: string;
  /** @nullable */
  name?: string | null;
  category: WatchlistItemCategory;
  condition: string;
  /** @nullable */
  priority?: number | null;
}
