/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Upstox Trade Suggestion System API
 * OpenAPI spec version: 0.1.0
 */

export type WatchlistItemCategory =
  (typeof WatchlistItemCategory)[keyof typeof WatchlistItemCategory];

export const WatchlistItemCategory = {
  MOMENTUM: "MOMENTUM",
  BREAKOUT_WATCH: "BREAKOUT_WATCH",
  GAP_CANDIDATE: "GAP_CANDIDATE",
  INTRADAY_BUY: "INTRADAY_BUY",
  INTRADAY_SELL: "INTRADAY_SELL",
  AVOID: "AVOID",
} as const;
